from .start_screen import StartScreen
from .search_screen import SearchHHScreen
from .detail_vacancy_screen import DetailVacancyScreen
from .favorites_vacancies_screen import FavoritesVacanciesScreen
from .detail_saved_vacancy_screen import DetailSavedVacancyScreen
